version: 0.2

batch:
  fast-fail: false 
  build-fanout:
    parallelism: 3
    ignore-failure: true
    
phases:
  install:
    commands:
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "Running codebuild-tests-run command using CODEBUILD_CURRENT_SHARD_FILES"
      - codebuild-tests-run --test-command 'npx jest $(echo "$CODEBUILD_CURRENT_SHARD_FILES" | tr "\n" " ")' --files-search "codebuild-glob-search '**/_tests_/**/*.test.js'" --sharding-strategy 'stability'
         
  post_build:
    commands:
      - codebuild-glob-search '**/*.xml'  
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"
